# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ad4ddc29685629e591744a4f4df8d860cc4748bc48da789678087257f713ee88fb2e34af1bc1fa4518c75dcb18001615aa7be3cb2f12b1698e76fa4f7740137

test:
  secret_key_base: fe3a92f81ac9ffbd76cb0c88ee3aba7bf34c87b3ab456d7a4f2a0a703df011c220583c0c202b594af3973152d4066a01134b24b663307145014ec80cd8576c17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
